# Generated by Django 3.1.4 on 2022-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220330_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learn',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='project',
            name='obstacles',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='project',
            name='successes',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='projects/static/img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=200),
        ),
    ]
