# Generated by Django 3.1.4 on 2022-04-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_motto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motto',
        ),
    ]
